/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CerezPolitikasiRouteImport } from './routes/cerez-politikasi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as KvkkRouteImport } from './routes/kvkk'
import { Route as OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRouteImport } from './routes/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as YeniWebSitemizYayindaRouteImport } from './routes/yeni-web-sitemiz-yayinda'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAyarlarRouteImport } from './routes/admin/ayarlar'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminGaleriRouteImport } from './routes/admin/galeri'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProjelerRouteImport } from './routes/admin/projeler'
import { Route as AdminTaleplerRouteImport } from './routes/admin/talepler'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ProjelerIndexRouteImport } from './routes/projeler/index'
import { Route as ProjelerSlugRouteImport } from './routes/projeler/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CerezPolitikasiRoute = CerezPolitikasiRouteImport.update({
  id: '/cerez-politikasi',
  path: '/cerez-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const KvkkRoute = KvkkRouteImport.update({
  id: '/kvkk',
  path: '/kvkk',
  getParentRoute: () => rootRouteImport,
} as any)
const OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRoute =
  OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRouteImport.update({
    id: '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler',
    path: '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const YeniWebSitemizYayindaRoute = YeniWebSitemizYayindaRouteImport.update({
  id: '/yeni-web-sitemiz-yayinda',
  path: '/yeni-web-sitemiz-yayinda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAyarlarRoute = AdminAyarlarRouteImport.update({
  id: '/admin/ayarlar',
  path: '/admin/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGaleriRoute = AdminGaleriRouteImport.update({
  id: '/admin/galeri',
  path: '/admin/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjelerRoute = AdminProjelerRouteImport.update({
  id: '/admin/projeler',
  path: '/admin/projeler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTaleplerRoute = AdminTaleplerRouteImport.update({
  id: '/admin/talepler',
  path: '/admin/talepler',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerIndexRoute = ProjelerIndexRouteImport.update({
  id: '/projeler/',
  path: '/projeler/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerSlugRoute = ProjelerSlugRouteImport.update({
  id: '/projeler/$slug',
  path: '/projeler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/contact': typeof ContactRoute
  '/galeri': typeof GaleriRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler': typeof OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/urunler': typeof UrunlerRoute
  '/yeni-web-sitemiz-yayinda': typeof YeniWebSitemizYayindaRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projeler': typeof AdminProjelerRoute
  '/admin/talepler': typeof AdminTaleplerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projeler/': typeof ProjelerIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/contact': typeof ContactRoute
  '/galeri': typeof GaleriRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler': typeof OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/urunler': typeof UrunlerRoute
  '/yeni-web-sitemiz-yayinda': typeof YeniWebSitemizYayindaRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projeler': typeof AdminProjelerRoute
  '/admin/talepler': typeof AdminTaleplerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projeler': typeof ProjelerIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/cerez-politikasi': typeof CerezPolitikasiRoute
  '/contact': typeof ContactRoute
  '/galeri': typeof GaleriRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/kvkk': typeof KvkkRoute
  '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler': typeof OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/urunler': typeof UrunlerRoute
  '/yeni-web-sitemiz-yayinda': typeof YeniWebSitemizYayindaRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/projeler': typeof AdminProjelerRoute
  '/admin/talepler': typeof AdminTaleplerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projeler/': typeof ProjelerIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/cerez-politikasi'
    | '/contact'
    | '/galeri'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/urunler'
    | '/yeni-web-sitemiz-yayinda'
    | '/admin/ayarlar'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/galeri'
    | '/admin/login'
    | '/admin/projeler'
    | '/admin/talepler'
    | '/blog/$slug'
    | '/projeler/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/blog/'
    | '/projeler/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/cerez-politikasi'
    | '/contact'
    | '/galeri'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/urunler'
    | '/yeni-web-sitemiz-yayinda'
    | '/admin/ayarlar'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/galeri'
    | '/admin/login'
    | '/admin/projeler'
    | '/admin/talepler'
    | '/blog/$slug'
    | '/projeler/$slug'
    | '/services/$slug'
    | '/admin'
    | '/blog'
    | '/projeler'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/cerez-politikasi'
    | '/contact'
    | '/galeri'
    | '/gizlilik-politikasi'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/kvkk'
    | '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/urunler'
    | '/yeni-web-sitemiz-yayinda'
    | '/admin/ayarlar'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/galeri'
    | '/admin/login'
    | '/admin/projeler'
    | '/admin/talepler'
    | '/blog/$slug'
    | '/projeler/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/blog/'
    | '/projeler/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  CerezPolitikasiRoute: typeof CerezPolitikasiRoute
  ContactRoute: typeof ContactRoute
  GaleriRoute: typeof GaleriRoute
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IletisimRoute: typeof IletisimRoute
  KvkkRoute: typeof KvkkRoute
  OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRoute: typeof OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  UrunlerRoute: typeof UrunlerRoute
  YeniWebSitemizYayindaRoute: typeof YeniWebSitemizYayindaRoute
  AdminAyarlarRoute: typeof AdminAyarlarRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGaleriRoute: typeof AdminGaleriRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProjelerRoute: typeof AdminProjelerRoute
  AdminTaleplerRoute: typeof AdminTaleplerRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProjelerSlugRoute: typeof ProjelerSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjelerIndexRoute: typeof ProjelerIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cerez-politikasi': {
      id: '/cerez-politikasi'
      path: '/cerez-politikasi'
      fullPath: '/cerez-politikasi'
      preLoaderRoute: typeof CerezPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kvkk': {
      id: '/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof KvkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler': {
      id: '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler'
      path: '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler'
      fullPath: '/ozel-olcu-mobilya-yaptirmadan-once-dikkat-edilmesi-gerekenler'
      preLoaderRoute: typeof OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yeni-web-sitemiz-yayinda': {
      id: '/yeni-web-sitemiz-yayinda'
      path: '/yeni-web-sitemiz-yayinda'
      fullPath: '/yeni-web-sitemiz-yayinda'
      preLoaderRoute: typeof YeniWebSitemizYayindaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ayarlar': {
      id: '/admin/ayarlar'
      path: '/admin/ayarlar'
      fullPath: '/admin/ayarlar'
      preLoaderRoute: typeof AdminAyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/galeri': {
      id: '/admin/galeri'
      path: '/admin/galeri'
      fullPath: '/admin/galeri'
      preLoaderRoute: typeof AdminGaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projeler': {
      id: '/admin/projeler'
      path: '/admin/projeler'
      fullPath: '/admin/projeler'
      preLoaderRoute: typeof AdminProjelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/talepler': {
      id: '/admin/talepler'
      path: '/admin/talepler'
      fullPath: '/admin/talepler'
      preLoaderRoute: typeof AdminTaleplerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler/': {
      id: '/projeler/'
      path: '/projeler'
      fullPath: '/projeler/'
      preLoaderRoute: typeof ProjelerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler/$slug': {
      id: '/projeler/$slug'
      path: '/projeler/$slug'
      fullPath: '/projeler/$slug'
      preLoaderRoute: typeof ProjelerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  CerezPolitikasiRoute: CerezPolitikasiRoute,
  ContactRoute: ContactRoute,
  GaleriRoute: GaleriRoute,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IletisimRoute: IletisimRoute,
  KvkkRoute: KvkkRoute,
  OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRoute:
    OzelOlcuMobilyaYaptirmadanOnceDikkatEdilmesiGerekenlerRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  UrunlerRoute: UrunlerRoute,
  YeniWebSitemizYayindaRoute: YeniWebSitemizYayindaRoute,
  AdminAyarlarRoute: AdminAyarlarRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGaleriRoute: AdminGaleriRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProjelerRoute: AdminProjelerRoute,
  AdminTaleplerRoute: AdminTaleplerRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProjelerSlugRoute: ProjelerSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjelerIndexRoute: ProjelerIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
